# --------------------------------------------------------------

# GET https://127.0.0.1:8000/api/articles/list

# --------------------------------------------------------------

# GET https://127.0.0.1:8000/api/articles/read/5

# --------------------------------------------------------------

# POST https://127.0.0.1:8000/api/articles/add

# {
#     "title": "Ajout par API",
#     "content": "<p>Contenu ajouté par l'API</p>",
#     "image": "test.jpg"
# }

# --------------------------------------------------------------

# PUT https://127.0.0.1:8000/api/articles/edit/8

# {
#     "title": "Édité par API",
#     "content": "<p>Contenu édité par l'API</p>",
#     "image": "test.jpg"
# }

# --------------------------------------------------------------

# DELETE  https://127.0.0.1:8000/api/articles/delete/5

# --------------------------------------------------------------
